version: '3.5'

services:
  fanuc_driver:
    container_name: fanuc_driver
    image: ladder99/fanuc-driver:latest
    restart: always
    depends_on:
      - mosquitto
    networks:
      - fanuc
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/fanuc-volumes/fanuc-driver:/etc/fanuc:rw
    logging:
      options:
        max-size: "20m"
  
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    networks:
      - fanuc
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/fanuc-volumes/mosquitto/config:/mosquitto/config:rw
      - ~/fanuc-volumes/mosquitto/data:/mosquitto/data:rw
      - ~/fanuc-volumes/mosquitto/log:/mosquitto/log:rw
    logging:
      driver: "json-file"
      options:
        max-size: "20m"

networks:
  fanuc:
    name: fanuc